// Code generated by protoc-gen-go.
// source: player.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	player.proto

It has these top-level messages:
	PlayerInfoRequest
	PlayerInfoResponse
	PlayerEntryRequest
	PlayerEntryResponse
	PlayerComment
	PlayerCommentRequest
	PlayerCommentResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlayerInfoRequest struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *PlayerInfoRequest) Reset()                    { *m = PlayerInfoRequest{} }
func (m *PlayerInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*PlayerInfoRequest) ProtoMessage()               {}
func (*PlayerInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PlayerInfoResponse struct {
	Id            uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Money         uint64 `protobuf:"varint,3,opt,name=money" json:"money,omitempty"`
	LastLoginedAt int64  `protobuf:"varint,4,opt,name=last_logined_at,json=lastLoginedAt" json:"last_logined_at,omitempty"`
}

func (m *PlayerInfoResponse) Reset()                    { *m = PlayerInfoResponse{} }
func (m *PlayerInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*PlayerInfoResponse) ProtoMessage()               {}
func (*PlayerInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PlayerEntryRequest struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *PlayerEntryRequest) Reset()                    { *m = PlayerEntryRequest{} }
func (m *PlayerEntryRequest) String() string            { return proto.CompactTextString(m) }
func (*PlayerEntryRequest) ProtoMessage()               {}
func (*PlayerEntryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type PlayerEntryResponse struct {
	PlayerId uint64   `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	EntryId  []uint32 `protobuf:"varint,2,rep,packed,name=entry_id,json=entryId" json:"entry_id,omitempty"`
}

func (m *PlayerEntryResponse) Reset()                    { *m = PlayerEntryResponse{} }
func (m *PlayerEntryResponse) String() string            { return proto.CompactTextString(m) }
func (*PlayerEntryResponse) ProtoMessage()               {}
func (*PlayerEntryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type PlayerComment struct {
	Id        uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	EntryId   uint32 `protobuf:"varint,2,opt,name=entry_id,json=entryId" json:"entry_id,omitempty"`
	Comment   string `protobuf:"bytes,3,opt,name=comment" json:"comment,omitempty"`
	CreatedAt int64  `protobuf:"varint,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt int64  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *PlayerComment) Reset()                    { *m = PlayerComment{} }
func (m *PlayerComment) String() string            { return proto.CompactTextString(m) }
func (*PlayerComment) ProtoMessage()               {}
func (*PlayerComment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type PlayerCommentRequest struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *PlayerCommentRequest) Reset()                    { *m = PlayerCommentRequest{} }
func (m *PlayerCommentRequest) String() string            { return proto.CompactTextString(m) }
func (*PlayerCommentRequest) ProtoMessage()               {}
func (*PlayerCommentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type PlayerCommentResponse struct {
	Id            uint64           `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	PlayerComment []*PlayerComment `protobuf:"bytes,2,rep,name=player_comment,json=playerComment" json:"player_comment,omitempty"`
}

func (m *PlayerCommentResponse) Reset()                    { *m = PlayerCommentResponse{} }
func (m *PlayerCommentResponse) String() string            { return proto.CompactTextString(m) }
func (*PlayerCommentResponse) ProtoMessage()               {}
func (*PlayerCommentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PlayerCommentResponse) GetPlayerComment() []*PlayerComment {
	if m != nil {
		return m.PlayerComment
	}
	return nil
}

func init() {
	proto.RegisterType((*PlayerInfoRequest)(nil), "pb.PlayerInfoRequest")
	proto.RegisterType((*PlayerInfoResponse)(nil), "pb.PlayerInfoResponse")
	proto.RegisterType((*PlayerEntryRequest)(nil), "pb.PlayerEntryRequest")
	proto.RegisterType((*PlayerEntryResponse)(nil), "pb.PlayerEntryResponse")
	proto.RegisterType((*PlayerComment)(nil), "pb.PlayerComment")
	proto.RegisterType((*PlayerCommentRequest)(nil), "pb.PlayerCommentRequest")
	proto.RegisterType((*PlayerCommentResponse)(nil), "pb.PlayerCommentResponse")
}

func init() { proto.RegisterFile("player.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0xdd, 0x4e, 0xf2, 0x40,
	0x10, 0xfd, 0x5a, 0x7e, 0x3b, 0x7c, 0xe5, 0x0b, 0xf3, 0x81, 0x16, 0x8c, 0x49, 0xd3, 0x0b, 0xd3,
	0x2b, 0xa2, 0x70, 0xe3, 0x8d, 0x89, 0xc4, 0x68, 0x42, 0xa2, 0x89, 0xe9, 0x0b, 0x90, 0x42, 0x57,
	0x43, 0x42, 0x77, 0xd7, 0x76, 0x31, 0xe1, 0x35, 0x7c, 0x33, 0xdf, 0xc8, 0x74, 0xb7, 0x85, 0x2d,
	0xa8, 0xe1, 0x8e, 0x39, 0x73, 0xce, 0xe1, 0xcc, 0xce, 0x14, 0xfe, 0xf2, 0x55, 0xb8, 0x21, 0xc9,
	0x90, 0x27, 0x4c, 0x30, 0x34, 0xf9, 0xdc, 0xbb, 0x84, 0xce, 0xb3, 0xc4, 0xa6, 0xf4, 0x85, 0x05,
	0xe4, 0x6d, 0x4d, 0x52, 0x81, 0x67, 0x60, 0x29, 0xe2, 0x6c, 0x19, 0x39, 0x86, 0x6b, 0xf8, 0xd5,
	0xa0, 0xa9, 0x80, 0x69, 0xe4, 0xbd, 0x03, 0xea, 0x8a, 0x94, 0x33, 0x9a, 0x12, 0x6c, 0x83, 0xb9,
	0xe5, 0x9a, 0xcb, 0x08, 0x11, 0xaa, 0x34, 0x8c, 0x89, 0x63, 0xba, 0x86, 0x6f, 0x05, 0xf2, 0x37,
	0x76, 0xa1, 0x16, 0x33, 0x4a, 0x36, 0x4e, 0x45, 0xd2, 0x54, 0x81, 0x17, 0xf0, 0x6f, 0x15, 0xa6,
	0x62, 0xb6, 0x62, 0xaf, 0x4b, 0x4a, 0xa2, 0x59, 0x28, 0x9c, 0xaa, 0x6b, 0xf8, 0x95, 0xc0, 0xce,
	0xe0, 0x47, 0x85, 0x4e, 0x84, 0x77, 0x55, 0xfc, 0xef, 0x3d, 0x15, 0xc9, 0xe6, 0xa8, 0xa8, 0x4f,
	0xf0, 0xbf, 0x24, 0xc9, 0xb3, 0xfe, 0xa6, 0xc1, 0x3e, 0x34, 0x49, 0xc6, 0xce, 0x7a, 0xa6, 0x5b,
	0xf1, 0xed, 0xa0, 0x21, 0xeb, 0x69, 0xe4, 0x7d, 0x18, 0x60, 0x2b, 0xbf, 0x3b, 0x16, 0xc7, 0x84,
	0x8a, 0x83, 0xa9, 0xcb, 0x62, 0x43, 0x13, 0xa3, 0x03, 0x8d, 0x85, 0x52, 0xc9, 0xf1, 0xad, 0xa0,
	0x28, 0xf1, 0x1c, 0x60, 0x91, 0x90, 0x50, 0xe8, 0xb3, 0x5b, 0x39, 0x32, 0x91, 0xed, 0x35, 0x8f,
	0x8a, 0x76, 0x4d, 0xb5, 0x73, 0x64, 0x22, 0xbc, 0x31, 0x74, 0x4b, 0x99, 0x8e, 0x7a, 0x98, 0x10,
	0x7a, 0x7b, 0xa2, 0x1f, 0xd6, 0x78, 0x0d, 0xed, 0xdc, 0xa5, 0x08, 0x9f, 0xbd, 0x49, 0x6b, 0xd4,
	0x19, 0xf2, 0xf9, 0xb0, 0x6c, 0x61, 0x73, 0xbd, 0x1c, 0x7d, 0x1a, 0x50, 0x57, 0x04, 0xbc, 0x01,
	0xd8, 0x5d, 0x0c, 0xf6, 0x76, 0x52, 0xed, 0xe6, 0x06, 0x27, 0xfb, 0xb0, 0x4a, 0xe4, 0xfd, 0xc1,
	0x5b, 0x68, 0x69, 0x5b, 0x44, 0x8d, 0xa8, 0x5f, 0xc2, 0xe0, 0xf4, 0x00, 0xdf, 0x3a, 0x3c, 0xec,
	0xef, 0xcd, 0x39, 0x8c, 0x9f, 0xbb, 0xf4, 0xbf, 0xe9, 0x14, 0x3e, 0xf3, 0xba, 0xfc, 0x6e, 0xc6,
	0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x6c, 0x84, 0xb7, 0x47, 0x03, 0x00, 0x00,
}
